### ISSUE TITLE
Center text and fix showing stars in watchers

### ISSUE THREAD

**Issue by SerekKiri** [SerekKiri/SerekKiri.github.io#1]
Center text here --> https://i.imgur.com/q9vtK3h.png

And fix this icons 😄 
https://imgur.com/a/GZ3AdVS

**Comment by lazycipher** [comment]
Hey! @SerekKiri ,

Can you please elaborate more!

**Comment by SerekKiri** [comment]
@lazycipher In watchers icon you can see number from stars icon  😄 , text in repository embed is in align to left (I want to center) and this github icon look's pretty bad in this button so you can remove it. 👍 
Now i don't have here nothing more to do 😃 but if you want you can show your ideas for changes in this website 👍

**Comment by lazycipher** [comment]
@SerekKiri  Got it !
I'll make changes and create a PR by Tomorrow the same time!
I've my papers so can't work now!

One last thing! Do you want to make the text, for example -  "angelhack2018"  exactly below "Serek Kiri" ?

**Comment by SerekKiri** [comment]
@lazycipher yop 💯

**Comment by lazycipher** [comment]
Got it!
I'll be working on it! :)

**Comment by lazycipher** [comment]
@SerekKiri  You agreed that I'll be working on it ! But you merged someone else's PR !!
No issues.
Happy Coding :+1:

**Comment by SerekKiri** [comment]
@lazycipher, you can still make PR, and show your version :grinning:. It will count on hacktoberfest! :+1:
